# Generated by Django 3.1.7 on 2021-04-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210410_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='heyzine_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
