const books = [
    {
      '_id': '1',
      'name': 'book1',
      'image': '/images/recreo.jpg',
      'description': '',
      'brand': '',
      'category': 'Adventure',
      'rating': 4.5,
      'numReviews': 12,
      'age' : 1,
    },
    {
      '_id': '2',
      'name': 'book2',
      'image': '/images/book2.jpg',
      'description':'',
      'brand': '',
      'category': 'Science',
      'rating': 4.0,
      'numReviews': 8,
      'age': 2,
    },
    {
      '_id': '3',
      'name': 'book3',
      'image': '/images/book3.jpg',
      'description':'',
      'brand': '',
      'category': 'Animals',
      'rating': 3,
      'numReviews': 12,
      'age': 3,
    },
    {
      '_id': '4',
      'name': 'book4',
      'image': '/images/book4.jpg',
      'description':'',
      'brand': '',
      'category': 'Animal',
      'rating': 5,
      'numReviews': 12,
      'age': 2,
    },
    {
      '_id': '5',
      'name': 'book5',
      'image': '/images/book5.jpg',
      'description':'',
      'brand': '',
      'category': 'Science',
      'rating': 3.5,
      'numReviews': 10,
      'age': 1,
    },
    
  ]
  export default books